services:
  casamento:
    container_name: casamento
    build:
      context: .
      dockerfile: Dockerfile.dev
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: local
      options:
        max-size: '10m'
        max-file: '10'
    restart: unless-stopped
    ports:
      - 3051:3000  
    volumes:
      - ./code:/app
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@host.docker.internal:5432/ticket?schema=public&connection_limit=5'
      ENVIRONMENT: 'localhost'
      NODE_ENV: 'development'
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: Stefanini@10
      REDIS_PORT: '6379'
